import { Box, HStack, AvatarGroup, Avatar } from "@chakra-ui/react";

export const AvatarIcon = () => {
  return (
    <>
      <Box ml={"29px"} mt={"20px"}>
        <HStack spacing={"10px"}>
          <AvatarGroup size={"md"} max={7} spacing={-1}>
            <Avatar src="https://media.licdn.com/dms/image/C4D03AQFcT-gcjMuPwQ/profile-displayphoto-shrink_800_800/0/1632494646958?e=2147483647&v=beta&t=W4GUISIt74rp6LLOE0ZSetPMdB9ZQH5K_KBlpxjEVHI" />
            <Avatar src="https://images.unsplash.com/photo-1618641986557-1ecd230959aa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" />
            <Avatar src="https://bit.ly/code-beast" />
            <Avatar src="https://bit.ly/ryan-florence" />
            <Avatar src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80" />
            <Avatar src="https://plus.unsplash.com/premium_photo-1675848493910-5474ee04c3e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" />
            <Avatar src="https://images.unsplash.com/photo-1634926878768-2a5b3c42f139?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60" />
            <Avatar src="https://images.unsplash.com/photo-1511367461989-f85a21fda167?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1631&q=80" />
            <Avatar src="https://images.unsplash.com/photo-1457449940276-e8deed18bfff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" />
            <Avatar src="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1143&q=80" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
            <Avatar src="https://bit.ly/dan-abramov" />
          </AvatarGroup>
        </HStack>
      </Box>
    </>
  );
};
